id: Vulnerability Management - Qualys (Job) - V2
version: -1
name: Vulnerability Management - Qualys (Job) - V2
description: |-
  Use the latest Qualys report to manage vulnerabilities.

  This playbook runs as a job, and by default creates incidents of type "Vulnerability" based on assets and vulnerabilities.
  The incidents are created from the latest version of the report determined by the report timestamp.
  You can define the minimum severity (minSeverity) that incidents are created for.
  Duplicate incidents are not created for the same asset ID and QID.

  This playbook is a part of a series of playbooks for Qualys vulnerability management and remediation.
  For this series of playbooks to run successfully, create a Job and do the following:
  1. Assign this playbook to the Job
  2. Enter the Qualys XML report name into the "Details" field
  3. Associate the "Vulnerability" type incident to the "Vulnerability Handling - Qualys" playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 34ca52c3-a771-4c92-853b-b72b8d8f517b
    type: start
    task:
      id: 34ca52c3-a771-4c92-853b-b72b8d8f517b
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: aaa87a5f-96ed-4937-8ea1-6ff1c9e9a81a
    type: regular
    task:
      id: aaa87a5f-96ed-4937-8ea1-6ff1c9e9a81a
      version: -1
      name: Get Qualys reports list
      description: Get a list of generated reports in the system
      script: QualysVulnerabilityManagementV2|||qualys-report-list
      type: regular
      iscommand: true
      brand: QualysVulnerabilityManagementV2
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 8a998018-6077-42eb-8b07-82e5819aba1a
    type: condition
    task:
      id: 8a998018-6077-42eb-8b07-82e5819aba1a
      version: -1
      name: Is there a valid report?
      description: Check if there's a Qualys report that matches the input report
        name and is in XML format.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "YES":
      - "11"
    separatecontext: false
    conditions:
    - label: "YES"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: QualysReport
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: QualysReport.TITLE
                      iscontext: true
                    right:
                      value:
                        simple: inputs.QualysReportTitle
                      iscontext: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: QualysReport.STATUS.STATE
                      iscontext: true
                    right:
                      value:
                        simple: Finished
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: QualysReport.OUTPUT_FORMAT
                      iscontext: true
                    right:
                      value:
                        simple: XML
                accessor: ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 6026f7dd-bc80-4545-8d57-12476605912d
    type: title
    task:
      id: 6026f7dd-bc80-4545-8d57-12476605912d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 64ad0352-fc55-4cbd-877d-1da559af9bf1
    type: title
    task:
      id: 64ad0352-fc55-4cbd-877d-1da559af9bf1
      version: -1
      name: Create incidents from the Qualys report
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 1a0cd45a-926b-4fa8-8b26-04cffa74d3e9
    type: regular
    task:
      id: 1a0cd45a-926b-4fa8-8b26-04cffa74d3e9
      version: -1
      name: Create incidents from the Qualys report
      description: |-
        Create incidents from a Qualys report (XML), based on the Qualys asset ID and vulnerability ID (QID).
        Duplicate incidents are not created for the same asset ID and QID.
      script: QualysCreateIncidentFromReport
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      entryID:
        complex:
          root: InfoFile
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: InfoFile.Info
                iscontext: true
              right:
                value:
                  simple: application/xml
          accessor: EntryID
      minSeverity:
        simple: ${inputs.MinSeverity}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: f2f3f3f8-0b24-4bb5-8fe9-2bfe5f1c33e0
    type: condition
    task:
      id: f2f3f3f8-0b24-4bb5-8fe9-2bfe5f1c33e0
      version: -1
      name: Is Qualys enabled?
      description: Verify that there's a valid instance of Qualys enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: QualysVulnerabilityManagement
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 73053224-7dd1-481b-80ec-e1cd452d9f22
    type: regular
    task:
      id: 73053224-7dd1-481b-80ec-e1cd452d9f22
      version: -1
      name: Get report
      description: Download report
      script: QualysVulnerabilityManagementV2|||qualys-report-fetch
      type: regular
      iscommand: true
      brand: QualysVulnerabilityManagementV2
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      file_format:
        simple: xml
      id:
        complex:
          root: QualysReport
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: QualysReport.TITLE
                iscontext: true
              right:
                value:
                  simple: inputs.QualysReportTitle
                iscontext: true
          - - operator: isEqualString
              left:
                value:
                  simple: QualysReport.STATUS.STATE
                iscontext: true
              right:
                value:
                  simple: Finished
              ignorecase: true
          - - operator: isEqualString
              left:
                value:
                  simple: QualysReport.OUTPUT_FORMAT
                iscontext: true
              right:
                value:
                  simple: XML
              ignorecase: true
          accessor: ID
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: be76cf2f-e175-4386-8a66-61f413904f0a
    type: regular
    task:
      id: be76cf2f-e175-4386-8a66-61f413904f0a
      version: -1
      name: Set context
      description: 'Set the Qualys reports list into context. '
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      key:
        simple: QualysReport
      value:
        complex:
          root: Qualys
          accessor: Report
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 76b7243d-96b0-4cd1-8f30-13015382d460
    type: regular
    task:
      id: 76b7243d-96b0-4cd1-8f30-13015382d460
      version: -1
      name: Close Investigation
      description: Close the investigation.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 279,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: f6dc7724-7ef9-47c5-8ec0-d7f72e614afb
    type: title
    task:
      id: f6dc7724-7ef9-47c5-8ec0-d7f72e614afb
      version: -1
      name: Get report from Qualys
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 609,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: QualysReportTitle
  value:
    complex:
      root: incident
      accessor: details
  required: true
  description: "The report title as it appears in Qualys.\nHas to be in XML format. "
  playbookInputQuery:
- key: MinSeverity
  value:
    simple: "3"
  required: true
  description: The minimum Qualys severity (1 -5) to create incidents for
  playbookInputQuery:
outputs: []
tests:
- QualysVulnerabilityManagement-Test
fromversion: 5.5.0
